### ISSUE TITLE
About replacing arrows with fontawesome icons

### ISSUE THREAD

**Issue by atefBB** [veksen/better-react-swiper#19]
Hey! What're your thoughts about replacing `arrows` (see https://github.com/atefBB/better-react-swiper/blob/master/src/index.tsx#L158) with `fontawesome` icons?

**Comment by veksen** [comment]
Hey! Good point. How about SVG arrows? I would prefer not depend on an external library like fontawesome just for the icons

**Comment by atefBB** [comment]
Yes. Good choice! I've think about yesterday it because I saw that Airbnb uses an `SVG` icon too.

**Comment by veksen** [comment]
Thanks for the feedback again, about to release an update on npm that uses svgs

**Comment by atefBB** [comment]
Thx.
