### ISSUE TITLE
Responsive solution

### ISSUE THREAD

**Issue by veksen** [veksen/better-react-swiper#7]
Figure out an element way to handle responsiveness.

First implementation could simply fallback to 1 element wide.

**Comment by mblarsen** [comment]
Version 0.2.0 seems to work fine on desktop when it comes responsiveness, but at some point it stops resizing the one element that is left. So as a result it is still wider than 100%.

![better-swiper-responsiveness](https://user-images.githubusercontent.com/247048/52922230-ae8c1500-335a-11e9-9f88-59652fb984d1.gif)

Perhaps I'm doing something wrong. You can see it here https://beta.codeboutique.com/cases (using 0.2.0)

**Comment by veksen** [comment]
fixed in da57013
